# .github/workflows/preview.yml
name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build
        uses: actions/jekyll-build-pages@v1
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
    
      - uses: rossjrw/pr-preview-action@v1
          with:
            source-dir: .
            preview-branch: main
            umbrella-dir: pr-preview
            action: auto
